package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"text/template"

	"github.com/getkin/kin-openapi/openapi3"
)

// Обновленный шаблон: только константы без кастомного типа
const tpl = `// Code generated by op-id-gen; DO NOT EDIT.
package {{.Package}}

const (
{{- range .IDs}}
	{{.}} = "{{.}}"
{{- end}}
)
`

func main() {
	specPath := flag.String("spec", "", "путь к собранному swagger файлу")
	outputPath := flag.String("out", "", "путь к выходному файлу")
	flag.Parse()

	if *specPath == "" || *outputPath == "" {
		fmt.Println("Использование: go run tools/gen-op-ids/main.go -spec <path> -out <path>")
		os.Exit(1)
	}

	loader := openapi3.NewLoader()
	doc, err := loader.LoadFromFile(*specPath)
	if err != nil {
		log.Fatalf("Ошибка загрузки спеки: %v", err)
	}

	uniqueIDs := make(map[string]struct{})
	for _, pathItem := range doc.Paths.Map() {
		for _, op := range pathItem.Operations() {
			if op.OperationID != "" {
				uniqueIDs[op.OperationID] = struct{}{}
			}
		}
	}

	ids := make([]string, 0, len(uniqueIDs))
	for id := range uniqueIDs {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	pkgName := filepath.Base(filepath.Dir(*outputPath))

	if err := os.MkdirAll(filepath.Dir(*outputPath), 0755); err != nil {
		log.Fatalf("Ошибка создания директорий: %v", err)
	}

	f, err := os.Create(*outputPath)
	if err != nil {
		log.Fatalf("Ошибка создания файла: %v", err)
	}
	defer f.Close()

	data := struct {
		Package string
		IDs     []string
	}{
		Package: pkgName,
		IDs:     ids,
	}

	t := template.Must(template.New("ids").Parse(tpl))
	if err := t.Execute(f, data); err != nil {
		log.Fatalf("Ошибка выполнения шаблона: %v", err)
	}

	fmt.Printf("✅ Константы OperationID созданы: %s (пакет: %s)\n", *outputPath, pkgName)
}
