// Code generated by swagger-ui-gen; DO NOT EDIT.
package swagger

import (
	"embed"
	"net/http"

	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

//go:embed bundles
var bundlesFS embed.FS

// Handler возвращает http.Handler с роутами для Swagger UI и спек всех версий.
// Подключай через mux.Mount("/swagger", swagger.Handler())
func Handler() http.Handler {
	r := chi.NewRouter()

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/swagger/v1/index.html", http.StatusFound)
	})

	r.Get("/v1/spec.json", func(w http.ResponseWriter, r *http.Request) {
		data, err := bundlesFS.ReadFile("bundles/v1.openapi.bundle.json")
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		w.Write(data)
	})

	r.Get("/v1/spec.yaml", func(w http.ResponseWriter, r *http.Request) {
		data, err := bundlesFS.ReadFile("bundles/v1.openapi.bundle.yaml")
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/yaml")
		w.Write(data)
	})

	r.Get("/v1/*", httpSwagger.Handler(
		httpSwagger.URL("/swagger/v1/spec.json"),
	))

	return r
}
