version: '3'

dotenv: ['.env']

vars:

  NODE_MODULES_BIN: "{{.ROOT_DIR}}/node_modules/.bin"
  REDOCLY: "{{.NODE_MODULES_BIN}}/redocly"

  OAPI_CODEGEN_VERSION: "v2.6.0"

  PROJECT_GOBIN: "{{.ROOT_DIR}}/go/bin"
  OAPI_CODEGEN: '{{.PROJECT_GOBIN}}/oapi-codegen'

  GO_API_APP_ENTRYPOINT: "{{.ROOT_DIR}}/cmd/api/main.go"

  OPEN_API_V1_SOURCE_FILE: "{{.ROOT_DIR}}/openapi/src/v1/v1.openapi.yaml"
  OPEN_API_V1_BUNDLE: "{{.ROOT_DIR}}/openapi/bundles/v1.openapi.bundle.yaml"

tasks:
  redocly-cli:install:
    desc: Установить локально Redocly CLI
    status:
     - "[ -f {{.REDOCLY}} ]"
    cmds:
      - echo "📦 Устанавливаем redocly-cli..."
      - npm ci

  redocly-v1:bundle:
    desc: Собрать OpenAPI v1 в один файл через локальный redocly 
    deps: [ redocly-cli:install ]
    cmds:
      - "{{.REDOCLY}} bundle {{.OPEN_API_V1_SOURCE_FILE}} -o {{.OPEN_API_V1_BUNDLE}}"
  
  oapi-codegen:install:
    desc: "Скачивает oapi-codegen в папку go/bin проекта"
    status: 
      - "[ -f {{.OAPI_CODEGEN}} ]"
    cmds:
       - echo "📦 Устанавливаем oapi-codegen..."
       - mkdir -p {{.PROJECT_GOBIN}}
       - GOBIN={{.PROJECT_GOBIN}} go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@{{.OAPI_CODEGEN_VERSION}}

  oapi-codegen-v1:gen:
    desc: "Генерация Go-кода из всех OpenAPI-декларации"
    deps: [ oapi-codegen:install ]
    cmds: 
      - task redocly-v1:bundle
      - "{{.OAPI_CODEGEN}} -config oapi-codegen.yaml {{.OPEN_API_V1_BUNDLE}}" 

  go-dev:run:
    desc: "Запуск go run"
    cmds:
      - go run {{.GO_API_APP_ENTRYPOINT}}


      


