package main

import (
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

const tpl = `// Code generated by swagger-ui-gen; DO NOT EDIT.
package {{.Package}}

import (
	"embed"
	"net/http"

	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

//go:embed bundles
var bundlesFS embed.FS

// Handler возвращает http.Handler с роутами для Swagger UI и спек всех версий.
// Подключай через mux.Mount("/swagger", swagger.Handler())
func Handler() http.Handler {
	r := chi.NewRouter()

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/swagger/{{.DefaultVersion}}/index.html", http.StatusFound)
	})
{{range .Versions}}
	r.Get("/{{.Version}}/spec.json", func(w http.ResponseWriter, r *http.Request) {
		data, err := bundlesFS.ReadFile("bundles/{{.BundleJSON}}")
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		w.Write(data)
	})

	r.Get("/{{.Version}}/spec.yaml", func(w http.ResponseWriter, r *http.Request) {
		data, err := bundlesFS.ReadFile("bundles/{{.BundleYAML}}")
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/yaml")
		w.Write(data)
	})

	r.Get("/{{.Version}}/*", httpSwagger.Handler(
		httpSwagger.URL("/swagger/{{.Version}}/spec.json"),
	))
{{end}}
	return r
}
`

type VersionInfo struct {
	Version    string
	BundleJSON string
	BundleYAML string
}

func main() {
	bundlesDir := flag.String("bundles", "", "путь к папке с бандлами")
	outputPath := flag.String("out", "", "путь к выходному файлу")
	packageName := flag.String("package", "", "имя пакета (опционально, по умолчанию берётся из папки output)")
	flag.Parse()

	if *bundlesDir == "" || *outputPath == "" {
		log.Fatal("Необходимо указать -bundles и -out")
	}

	matches, err := filepath.Glob(filepath.Join(*bundlesDir, "*.openapi.bundle.json"))
	if err != nil {
		log.Fatalf("Ошибка поиска бандлов: %v", err)
	}
	if len(matches) == 0 {
		log.Fatalf("Не найдено ни одного *.openapi.bundle.json в %s", *bundlesDir)
	}

	var versions []VersionInfo
	for _, match := range matches {
		base := filepath.Base(match)
		version := strings.TrimSuffix(base, ".openapi.bundle.json")
		versions = append(versions, VersionInfo{
			Version:    version,
			BundleJSON: base,
			BundleYAML: version + ".openapi.bundle.yaml",
		})
	}
	sort.Slice(versions, func(i, j int) bool {
		return versions[i].Version < versions[j].Version
	})

	pkg := sanitizePackage(filepath.Base(filepath.Dir(*outputPath)))
	if *packageName != "" {
		pkg = sanitizePackage(*packageName)
	}

	outDir := filepath.Dir(*outputPath)
	bundlesDest := filepath.Join(outDir, "bundles")
	if err := os.MkdirAll(bundlesDest, 0755); err != nil {
		log.Fatalf("Ошибка создания папки bundles: %v", err)
	}
	for _, v := range versions {
		for _, filename := range []string{v.BundleJSON, v.BundleYAML} {
			src := filepath.Join(*bundlesDir, filename)
			dst := filepath.Join(bundlesDest, filename)
			if err := copyFile(src, dst); err != nil {
				log.Fatalf("Ошибка копирования %s: %v", filename, err)
			}
		}
	}

	f, err := os.Create(*outputPath)
	if err != nil {
		log.Fatalf("Ошибка создания файла: %v", err)
	}
	defer f.Close()

	data := struct {
		Package        string
		Versions       []VersionInfo
		DefaultVersion string
	}{
		Package:        pkg,
		Versions:       versions,
		DefaultVersion: versions[0].Version,
	}

	t := template.Must(template.New("swagger").Parse(tpl))
	if err := t.Execute(f, data); err != nil {
		log.Fatalf("Ошибка генерации: %v", err)
	}

	fmt.Printf("✅ Swagger UI handler записан: %s\n", *outputPath)
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, in)
	return err
}

func sanitizePackage(s string) string {
	return strings.NewReplacer("-", "_", ".", "_").Replace(s)
}
