// Code generated by op-id-gen; DO NOT EDIT.
package operations_v2_beta

// Operation IDs
const (
	GetTaskByID = "GetTaskByID"
	PatchTaskByID = "PatchTaskByID"
)

// Middleware Names
const (
	MwAdmin = "admin"
	MwAuth = "auth"
)

var PathToOperationID = map[string]string{
	"GET /api/v2-beta/tasks/{id}": GetTaskByID,
	"PATCH /api/v2-beta/tasks/{id}": PatchTaskByID,
}

var OperationMiddlewares = map[string][]string{
	GetTaskByID: {
		MwAuth,
		MwAdmin,
	},
	PatchTaskByID: {
		MwAdmin,
		MwAuth,
	},
}
