parameters:
  - $ref: ../params/id.yaml

get:
  summary: Get task by id
  operationId: GetTaskByID
  tags:
    - Task
  responses:
    '200':
      description: Task information successfully retrieved
      content:
        application/json:
          schema:
            $ref: ../components/task.yaml
    '404':
      description: Task data for specified id not found
      content:
        application/json:
          schema:
            $ref: ../components/errors/error.yaml
    '400':
      description: Bad request - validation error
      content:
        application/json:
          schema:
            $ref: ../components/errors/validation_error.yaml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../components/errors/error.yaml
    default:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: ../components/errors/error.yaml
