// Code generated by op-id-gen; DO NOT EDIT.
package operations_v1

const (
	GetTaskByID = "GetTaskByID"
	PatchTaskByID = "PatchTaskByID"
)

// PathToOperationID мапит "METHOD Path" на OperationID
// Пример ключа: "GET /api/v1/tasks/{id}"
var PathToOperationID = map[string]string{
	"GET /tasks/{id}": GetTaskByID,
	"PATCH /tasks/{id}": PatchTaskByID,
}
