openapi: 3.0.3
info:
  title: Task Service API v1
  version: 1.0.0
  description: API v1 для работы с данными о задачах!

servers:
  - url: /api/v1
    description: v1 prefix

tags:
  - name: Task
    description: Операции с данными о задачах — получение и обновление информации

paths:
 /tasks/{id}:
    $ref: ./tasks/paths/task_by_id.yaml