openapi: 3.0.3
info:
  title: Task Service API v1
  version: 1.0.0
  description: API v1 для работы с данными о задачах!

tags:
  - name: Task
    description: Операции с данными о задачах — получение и обновление информации

paths:
 /api/v1/tasks/{id}:
    $ref: ./tasks/paths/task_by_id.yaml