openapi: 3.0.3
info:
  title: Task Service API
  version: 1.0.0
  description: API для работы с данными о задачах!
tags:
  - name: Task
    description: Операции с данными о задачах — получение и обновление информации
paths:
  /api/v1/tasks/{id}:
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      summary: Get task by id
      operationId: GetTaskByID
      tags:
        - Task
      responses:
        '200':
          description: Task information successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task'
        '400':
          description: Bad request - validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validation_error'
        '404':
          description: Task data for specified id not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  parameters:
    id:
      name: id
      in: path
      required: true
      description: id задачи
      schema:
        type: string
        format: uuid
        example: acde070d-8c4c-4f0d-9d8a-162843c10333
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Описание ошибки
          example: Ресурс не найден
    status:
      type: string
      description: |
        Текущее состояние жизненного цикла задачи: * `backlog` - Задача создана, но еще не взята в работу. * `in_progress` - Над задачей ведется работа. * `on_hold` - Работа приостановлена (ждем ответа, заблокирована). * `completed` - Задача успешно выполнена. * `canceled` - Задача отменена и не будет выполнена.
      enum:
        - backlog
        - in_progress
        - on_hold
        - completed
        - canceled
      example: in_progress
    task:
      type: object
      required:
        - id
        - title
        - is_active
        - status
        - created_at
      properties:
        id:
          type: string
          description: ID задачи
          format: uuid
          example: acde070d-8c4c-4f0d-9d8a-162843c10333
        title:
          type: string
          description: Заголовок задачи
          example: Задача 1
        is_active:
          type: boolean
          description: Отвечает за скрытость или видимость задачи
          example: true
        status:
          $ref: '#/components/schemas/status'
        created_at:
          type: string
          format: date-time
          description: Время создания задачи
          example: '2023-05-15T10:30:00Z'
    validation_error_item:
      type: object
      required:
        - field
        - error
      properties:
        field:
          type: string
          description: Поле у которого есть ошибка
          example: Username
        error:
          type: string
          description: Описание ошибки
          example: Username должен быть более 4 символов
    validation_error:
      type: object
      required:
        - message
        - errors
      properties:
        message:
          type: string
          description: Описание ошибки
          example: Ошибка валидации
        errors:
          type: array
          description: Список полей с ошибками валидации
          items:
            $ref: '#/components/schemas/validation_error_item'
