package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/getkin/kin-openapi/openapi3"
)

const tpl = `// Code generated by op-id-gen; DO NOT EDIT.
package {{.Package}}

// Operation IDs
const (
{{- range .IDs}}
	{{.}} = "{{.}}"
{{- end}}
)

// Middleware Names
const (
{{- range .MwConsts}}
	{{.Name}} = "{{.Value}}"
{{- end}}
)

var PathToOperationID = map[string]string{
{{- range $key, $id := .PathMap}}
	"{{$key}}": {{$id}},
{{- end}}
}

var OperationMiddlewares = map[string][]string{
{{- range $id, $mws := .OpMiddlewares}}
	{{$id}}: {
		{{- range $mws}}
		{{$.MwPrefix}}{{. | title}},
		{{- end}}
	},
{{- end}}
}
`

type MwConst struct {
	Name  string
	Value string
}

func title(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func main() {
	specPath := flag.String("spec", "", "путь к swagger")
	outputPath := flag.String("out", "", "путь к выходу")
	flag.Parse()

	loader := openapi3.NewLoader()
	doc, err := loader.LoadFromFile(*specPath)
	if err != nil {
		log.Fatalf("Ошибка загрузки: %v", err)
	}

	uniqueIDs := make(map[string]struct{})
	uniqueMws := make(map[string]struct{})
	pathMap := make(map[string]string)
	opMiddlewares := make(map[string][]string)

	const mwPrefix = "Mw"

	for path, pathItem := range doc.Paths.Map() {
		for method, op := range pathItem.Operations() {
			if op.OperationID != "" {
				uniqueIDs[op.OperationID] = struct{}{}
				key := fmt.Sprintf("%s %s", strings.ToUpper(method), path)
				pathMap[key] = op.OperationID

				if ext, ok := op.Extensions["x-operation-middlewares"]; ok {
					if mws, ok := ext.([]interface{}); ok {
						for _, mw := range mws {
							if s, ok := mw.(string); ok {
								uniqueMws[s] = struct{}{}
								opMiddlewares[op.OperationID] = append(opMiddlewares[op.OperationID], s)
							}
						}
					}
				}
			}
		}
	}

	// Сортировка для стабильной генерации
	ids := sortKeys(uniqueIDs)
	mws := sortKeys(uniqueMws)

	mwConsts := make([]MwConst, 0, len(mws))
	for _, m := range mws {
		mwConsts = append(mwConsts, MwConst{
			Name:  mwPrefix + title(m),
			Value: m,
		})
	}

	data := struct {
		Package       string
		IDs           []string
		MwConsts      []MwConst
		PathMap       map[string]string
		OpMiddlewares map[string][]string
		MwPrefix      string
	}{
		Package:       filepath.Base(filepath.Dir(*outputPath)),
		IDs:           ids,
		MwConsts:      mwConsts,
		PathMap:       pathMap,
		OpMiddlewares: opMiddlewares,
		MwPrefix:      mwPrefix,
	}

	f, _ := os.Create(*outputPath)
	defer f.Close()

	funcMap := template.FuncMap{"title": title}
	t := template.Must(template.New("ids").Funcs(funcMap).Parse(tpl))
	t.Execute(f, data)
}

func sortKeys(m map[string]struct{}) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
