package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/getkin/kin-openapi/openapi3"
)

// Шаблон генерирует константы и мапу для сопоставления роутов с ID
const tpl = `// Code generated by op-id-gen; DO NOT EDIT.
package {{.Package}}

const (
{{- range .IDs}}
	{{.}} = "{{.}}"
{{- end}}
)

// PathToOperationID мапит "METHOD Path" на OperationID
// Пример ключа: "GET /api/v1/tasks/{id}"
var PathToOperationID = map[string]string{
{{- range $key, $id := .PathMap}}
	"{{$key}}": {{$id}},
{{- end}}
}
`

func main() {
	specPath := flag.String("spec", "", "путь к собранному swagger файлу")
	outputPath := flag.String("out", "", "путь к выходному файлу")
	// Добавим префикс, так как в коде обычно используется r.Mount("/api/v1", ...)
	pathPrefix := flag.String("prefix", "", "префикс пути (например, /api/v1)")
	flag.Parse()

	if *specPath == "" || *outputPath == "" {
		fmt.Println("Использование: go run main.go -spec <path> -out <path> [-prefix /api/v1]")
		os.Exit(1)
	}

	loader := openapi3.NewLoader()
	doc, err := loader.LoadFromFile(*specPath)
	if err != nil {
		log.Fatalf("Ошибка загрузки спецификации: %v", err)
	}

	uniqueIDs := make(map[string]struct{})
	// Карта: "METHOD /path" -> OperationID
	pathMap := make(map[string]string)

	for path, pathItem := range doc.Paths.Map() {
		for method, op := range pathItem.Operations() {
			if op.OperationID != "" {
				uniqueIDs[op.OperationID] = struct{}{}

				// Чистим метод (делаем его UPPERCASE) и склеиваем с префиксом
				fullPath := *pathPrefix + path
				key := fmt.Sprintf("%s %s", strings.ToUpper(method), fullPath)

				pathMap[key] = op.OperationID
			}
		}
	}

	// Сортируем ID для стабильной генерации (чтобы файл не менялся при каждом запуске)
	ids := make([]string, 0, len(uniqueIDs))
	for id := range uniqueIDs {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	// Определяем имя пакета по папке назначения
	pkgName := filepath.Base(filepath.Dir(*outputPath))

	if err := os.MkdirAll(filepath.Dir(*outputPath), 0755); err != nil {
		log.Fatalf("Ошибка создания директорий: %v", err)
	}

	f, err := os.Create(*outputPath)
	if err != nil {
		log.Fatalf("Ошибка создания файла: %v", err)
	}
	defer f.Close()

	data := struct {
		Package string
		IDs     []string
		PathMap map[string]string
	}{
		Package: pkgName,
		IDs:     ids,
		PathMap: pathMap,
	}

	t := template.Must(template.New("ids").Parse(tpl))
	if err := t.Execute(f, data); err != nil {
		log.Fatalf("Ошибка выполнения шаблона: %v", err)
	}

	fmt.Printf("✅ Файл сгенерирован: %s (найдено %d операций)\n", *outputPath, len(ids))
}
